---
title: "Lab 06 - Conveying the right message through visualisation"
author: "DAF"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```


### Exercise 1

```{r create-data}
df <- tribble(
  ~date, ~count_mask, ~count_no_mask, 
  "7/12/2020", 25.2, 9.8,
  "7/13/2020", 19.8, 9.1,
  "7/14/2020", 19.7, 9.8,
  "7/15/2020", 20.5, 9.9,
  "7/16/2020", 19.7, 9.5,
  "7/17/2020", 19.7, 9.5,
  "7/18/2020", 19.9, 9.0,
  "7/19/2020", 20.6, 8.55,
  "7/20/2020", 21.5, 8.6,
  "7/21/2020", 19.7, 8.8,
  "7/22/2020", 19.7, 8.6,
  "7/23/2020", 20.4, 9.85,
  "7/24/2020", 19.0, 9.9,
  "7/25/2020", 19.7, 10.1,
  "7/26/2020", 17.0, 9.5,
  "7/27/2020", 16.2, 9.6,
  "7/28/2020", 16.4, 9.7,
  "7/29/2020", 16.5, 10.0,
  "7/30/2020", 16.0, 8.9,
  "7/31/2020", 16.1, 9.0,
  "8/1/2020", 15.8, 8.9,
  "8/2/2020", 15.9, 9.1,
  "8/3/2020", 16.0, 9.0,
)
```


### Exercise 2

```{r better-viz}
df2 <- df %>% pivot_longer(cols = c("count_mask", "count_no_mask"), 
                    names_to = "mask_bool", 
                    values_to = "values")

ggplot(df2, aes(x = date, y = values, group = mask_bool, colour = mask_bool)) + 
  geom_line() +
  theme(
    axis.text.x = element_text(angle = 45)
    )

```


### Exercise 3

*Add your narrative here.*


### Exercise 4

*Add your narrative here.*
